### ISSUE TITLE
Please Support Mongo Replica Set Connection Thanks😄

### ISSUE THREAD

**Issue by luckypig3400** [cylab-tw/raccoon#16]
### feat: support Mongo Replica Set Connection
+ https://github.com/luckypig3400/raccoon/commit/10d596f538a2fcedc16777851a76b89a16d72b86

### feat: Add Mongo Replica Set for Raccoon
+ https://github.com/luckypig3400/raccoon/commit/4b5ab1ec5249bd972c45460623e35bcccfc7096c

**Comment by Chinlinlee** [comment]
Thank you very much for your suggestion. 
Whether to use MongoDB Replica depends on the raccoon users' scenario.
I welcome you to share your MongoDB Replica configuration in the [Discussion](https://github.com/cylab-tw/raccoon/discussions).

I add `MONGODB_OPTIONS` to the `.env` file (8d66f1c), allowing you to add options to the MongoDB Connection URL by yourself.
In your use case, you can set `MONGODB_OPTIONS="directConnection=true"` to support replica connection.
