### ISSUE TITLE
Please support python without Anaconda in windows configuration! Thanks a lot 😄

### ISSUE THREAD

**Issue by luckypig3400** [cylab-tw/raccoon#4]
# Hello author, thanks for your amazing project!

## A few bugs occurred while I was deploying this project on my laptop(Win10).

I tried to install Anaconda and set up 'gdcm' environment with python 3.7 but in the end, it all lead to the same Error: ["ImportError: DLL load failed:"](https://stackoverflow.com/questions/41365446/how-to-resolve-importerror-dll-load-failed-on-python)

## Package 'pydicom' & 'gdcm' may support windows without Anaconda

So, I tried to install the required python packages with the python (which was installed on my laptop directly)
Then I found this great news, it could be installed with python 3.7.9 without Anaconda environment!
🔽  more information below 🔽
![](https://i.imgur.com/pOryYSd.png)

## Please support python without Anaconda in windows configuration! Thanks a lot 😄

**Comment by Chinlinlee** [comment]
Sounds very great👍. 
I will try to test the GDCM package provided by python in the windows environment and remove the description about anaconda.
And, I'm sorry that I forget to remove the version of **pydicom, the currently used version is higher than  2**.

**Comment by Chinlinlee** [comment]
Hi, I push the new code([dea2e48](https://github.com/cylab-tw/raccoon/commit/dea2e487a96a5059e7f2d1d53dc90b53c0837c18)) that add the feature which you advised.
Now, you can configure need to use the Anaconda or not.
To configure, please add `USE_CONDA=false` in `.env` file.

I also found the fantastic package called [python-gdcm](https://pypi.org/project/python-gdcm/) which can use in python and tested it can run [DICOM2JPEGFrame.py](https://github.com/cylab-tw/raccoon/blob/main/DICOM2JPEGFrame.py) without the Anaconda environment completely. Excellent🎉.

**Comment by luckypig3400** [comment]
![image](https://user-images.githubusercontent.com/25383278/157826363-51b4daaa-1953-452d-ac20-2d2d3ab6037c.png)

**Comment by luckypig3400** [comment]
## Much Appreciate! Now it works properly on Win10 😸
