### ISSUE TITLE
Incorrect way to convert 00080061 to FHIR

### ISSUE THREAD

**Issue by Chinlinlee** [cylab-tw/raccoon#6]
In `DICOM2FHIRImagingStudy.js` line 213
```js
studyobj.modality = DCMstring(json, '00080061');
```
The code read 00080061 tag of DICOM which the tag is only used for querying.
Need to find another way to convert the value of 00080061 tag to modalities in the study of FHIR ImagingStudy.

**Comment by cylien** [comment]
Please refer to DICOM Tag Mapping in FHIR ImagingStudy.
https://build.fhir.org/imagingstudy-mappings.html

Deal with the DICOM tag listed on the mapping table. Also, it is possible to process the DICOM tags listed on a DICOM tag list which could be added in Raccoon.
