### ISSUE TITLE
dicom影像沒有顯示出來

### ISSUE THREAD

**Issue by PenziSu** [cylab-tw/raccoon#8]
學長(們) 好:

我有兩個問題想請教
1. 本院自行上傳的dicom影像無法於bluelight顯示?
2. 為了執行mainecoon專案，請問如何確認DICOMWeb已經成功安裝?

謝謝

以下是操作過程：

我按照安裝步驟在本機完成raccoon & Bluelight兩個專案的安裝

接著從raccoon上傳dicom影像，分別有【手冊提供的測試影像】以及【本院的dicom影像】
(本院的dicom影像是三組去識別的CT影像)

dicom影像上傳過程順利無異常

執行<View in BlueLight DICOM Viwer>按鈕後，只有【手冊提供的測試影像】可於bluelight顯示
(Philips Amy的影像有密集的直線線條，Robert Huron則正常顯示)

【本院的dicom影像】無法於Bluelight顯示

我在Bluelight點擊資料夾圖案手動載入【本院的dicom影像】可以顯示出來

為了確認raccoon 有將dicom影像儲存下在。我從網址複製StudyInstanceUID，到資料表dicomBulkData查詢，資料庫紀錄的filename確實可以在資料夾內找到相同名稱的檔案

再來，為了確認是否因程式碼出錯，造成影像無法呈現，我開啟瀏覽器<開發者模式>並重新整理視窗多次，都沒有看到錯誤訊息出現。命令提示字元(cmd)同樣沒有錯誤訊息。

**Comment by Chinlinlee** [comment]
@PenziSu 您好
1. 可否請您開啟<開發者模式>中的 network 查看與 QIDO-RS 以及 WADO-RS or WADO-URI 相關的 request 是否跳出非 200 Status code，如下圖
![network](https://user-images.githubusercontent.com/49154622/183629571-726e806f-355c-4262-adf1-8da9c3b18122.png)
2. 病理影像與 Raccoon DICOMweb 的溝通是使用 [Retrieve Transaction Rendered Resources](https://dicom.nema.org/medical/dicom/current/output/html/part18.html#table_10.4.1-3) 中的 Rendered Frames (	/studies/{study}/series/{series}/instances/{instance}/frames/{frames}/rendered)，您可以使用任何一張您上傳的病理影像依照此網址填入，有在瀏覽器跳出 jpg 影像就代表 rendered frame 的功能是正常的

**Comment by PenziSu** [comment]
學長你好:

謝謝這麼快回覆。

經過指引，我調整了下圖紅框處的設定後，<network >就出現了[wado?requestType=WADO...]的錯誤訊息。
![2022-08-09_211602](https://user-images.githubusercontent.com/3418892/183656759-bf86f8bb-c3a4-4b47-8f43-77947787062d.png)

錯誤訊息如下圖，是http 404的錯誤
![2022-08-09_212108](https://user-images.githubusercontent.com/3418892/183657547-7790e79b-df65-4423-80a0-2f7324ed388c.png)

不知道是什麼地方沒有設定正確，再請學長指點

謝謝

**Comment by Chinlinlee** [comment]
> 經過指引，我調整了下圖紅框處的設定後，就出現了[wado?requestType=WADO...]的錯誤訊息。 ![2022-08-09_211602](https://user-images.githubusercontent.com/3418892/183656759-bf86f8bb-c3a4-4b47-8f43-77947787062d.png)

@PenziSu
Raccoon 的 WADO-URI API path 是 `api/dicom/wado`，請您將圖中 `WADO-URI` 的 `wado` 數值修改為 `api/dicom/wado`  試試看

**Comment by PenziSu** [comment]
謝謝學長的協助，調整設定後從raccoon點選bluelight的連結已經可以看到影像。

我發現其他專案(如: BL/search、mainecoon/bluelight-WSI、mainecoon/search)的設定檔都長得很像，請問是否比照設定就可以了呢?

謝謝

**Comment by cylien** [comment]
> 我發現其他專案(如: BL/search、mainecoon/bluelight-WSI、mainecoon/search)的設定檔都長得很像，請問是否比照設定就可以了呢?

YES, 這些設定都是一樣的，但要注意如果Search跟Raccoon連接，如果mainecoon跟BlueLight不是放在Raccoon的Public folder, Raccoon需要設定CORS才能連接。

如果醫院有DICOMweb Server也可以直接界接。

**Comment by PenziSu** [comment]
> > 我發現其他專案(如: BL/search、mainecoon/bluelight-WSI、mainecoon/search)的設定檔都長得很像，請問是否比照設定就可以了呢?
> 
> YES, 這些設定都是一樣的，但要注意如果Search跟Raccoon連接，如果mainecoon跟BlueLight不是放在Raccoon的Public folder, Raccoon需要設定CORS才能連接。
> 
> 如果醫院有DICOMweb Server也可以直接界接。

謝謝老師跟學長的指點，我實作看看。
謝謝。
